server: 
  port: 8761

spring: 
  security: 
    user: 
      name: aaa
      password: bbb
    
eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://aaa:bbb@localhost:8761/eureka/